services:
    app.mailer:
        class: AppBundle\Service\MailService
        arguments: ["@swiftmailer.mailer"]

    app.printer:
        class: AppBundle\Service\PrintService
        arguments: ["%printer_ip%", "@twig"]

    app.dispatcher:
        class: AppBundle\Service\DispatchService
        arguments: [["@app.mailer", "@app.printer"]]

    app.fortune:
        class: AppBundle\Service\FortuneService
        arguments: ["%fortune_path%"]


    app.twig.wordwrap:
        class: AppBundle\Twig\Extension\WordwrapExtension
        arguments: ["@app.fortune"]
        public: false
        tags:
            - { name: twig.extension }