services:
    app.repository.firefighter:
        class: AppBundle\Repository\FirefighterRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Firefighter

    app.mailer:
        class: AppBundle\Service\MailService
        arguments: ["@swiftmailer.mailer"]

    app.printer:
        class: AppBundle\Service\PrintService
        arguments: ["%printer_ip%", "@twig", "@app.repository.firefighter"]

    app.dispatcher:
        class: AppBundle\Service\DispatchService
        arguments: [["@app.mailer", "@app.printer"]]

    app.fortune:
        class: AppBundle\Service\FortuneService
        arguments: ["%fortune_path%"]


    app.twig.wordwrap:
        class: AppBundle\Twig\Extension\WordwrapExtension
        arguments: ["@app.fortune"]
        public: false
        tags:
            - { name: twig.extension }

    app.jira:
        class: AppBundle\Service\JiraIssueService
        arguments: ["@jms_serializer"]
        public: true